CFG_TOKEN:
  ACCESS_TOKEN_EXPIRE_MINUTES: 60
  REFRESH_TOKEN_EXPIRE_DAYS: 7

CFG_REDIS:
  host: 127.0.0.1
  port: 6379
  db  : 0
  user: 
  password: 
  type: 

CFG_SOCKET:
  host: 192.168.31.210
  # host: 127.0.0.1
  port: 9100

CFG_SERVER:
  host: 0.0.0.0
  port: 5000
